server:
  port: 8185

spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2   #Default is  /h2-console
      settings:
        trace: false #Default is also false
        web-allow-others: false #Default is also false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:      naming:        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        